pkg: fix pwrrt package for debian x86_64
(cherry picked from commit 3c647fc3829441798185ec979420809cc6885f17)

diff --git a/src/tools/pkg/deb_x86_64/pwrrt/postinst b/src/tools/pkg/deb_x86_64/pwrrt/postinst
--- a/src/tools/pkg/deb_x86_64/pwrrt/postinst
+++ b/src/tools/pkg/deb_x86_64/pwrrt/postinst
@@ -16,176 +16,125 @@ proot="/pwrp"
 aroot="/usr/pwrp/adm"
 
 # Create users...
-new_user=0
-
-if getent group pwrp > /dev/null; then
-  echo "-- group pwrp already exist"
-else
-  if groupadd pwrp; then
-    echo "-- group pwrp added"
+echo "-- Creating users/groups..."
+for grp in pwrp b55 b66 skiftel; do
+  if getent group ${grp} >/dev/null; then
+    echo "-- Group ${grp} already exist. OK!"
+  else
+    if groupadd ${grp}; then
+      echo "-- Group ${grp} added..."
+    fi
   fi
-fi
+done
 
-if getent group b55 > /dev/null; then
-  echo "-- group b55 already exist"
+# Do we have a pwrp user already?
+if getent passwd pwrp >/dev/null; then
+  echo "-- User pwrp already exist. OK!"
 else
-  if groupadd b55; then
-    echo "-- group b55 added"
+  if useradd --create-home --shell /bin/bash --password aaupl/kQs1p3U --gid pwrp --groups b55,b66,skiftel --home-dir /home/pwrp pwrp; then
+    echo "-- User pwrp added..."
   fi
-fi
 
-if getent group b66 > /dev/null; then
-  echo "-- group b66 already exist"
-else
-  if groupadd b66; then
-    echo "-- group b66 added"
-  fi
-fi
-
-if getent group skiftel > /dev/null; then
-  echo "-- group skiftel already exist"
-else
-  if groupadd skiftel; then
-    echo "-- group skiftel added"
-  fi
-fi
-
-if getent passwd pwrp > /dev/null; then
-  echo "-- user pwrp already exist"
-else
-  new_user=1
-
-  if useradd -s /bin/bash -p aaupl/kQs1p3U -g pwrp -G b55,b66,skiftel -d /home/pwrp pwrp; then
-    echo "-- user pwrp added"
-  fi
-  if [ ! -e /home/pwrp ]; then
-    mkdir /home/pwrp
-    cp /usr/pwrrt/cnf/user/.bashrc /home/pwrp
-    cp /usr/pwrrt/cnf/user/.bash_profile /home/pwrp
-#    cp /usr/pwrrt/cnf/user/.mwmrc /home/pwrp
+  # If all went well we copy proview specific startup scripts to the home folder
+  if [ -e /home/pwrp ]; then
     cp /usr/pwrrt/cnf/user/.rtt_start /home/pwrp
     chmod a+x /home/pwrp/.rtt_start
     cp /usr/pwrrt/cnf/user/.xtt_start /home/pwrp
     chmod a+x /home/pwrp/.xtt_start
-#    cp /usr/pwrrt/cnf/user/.xsession /home/pwrp
-
-    chown -R pwrp /home/pwrp
-    chgrp -R pwrp /home/pwrp
   fi
 
-  # Add to group dialout
-  if getent group dialout > /dev/null; then
-    usermod -a -G dialout pwrp
+  # Add pwrp to group dialout
+  if getent group dialout >/dev/null; then
+    usermod -a -G dialout pwrp && echo "-- User 'pwrp' added to group 'dialout'..." || echo "-- Unable to add user 'pwrp' to group 'dialout'!"
   fi
 fi
 
-if getent passwd skiftel > /dev/null; then
-  echo "-- user skiftel already exist"
+if getent passwd skiftel >/dev/null; then
+  echo "-- User skiftel already exist. OK!"
 else
-  new_user=1
-
-  if useradd -s /bin/bash -p aa6NzxS/aBgP6 -g skiftel -G pwrp -d /home/skiftel skiftel; then
-    echo "-- user skiftel added"
+  if useradd --create-home --shell /bin/bash --password aa6NzxS/aBgP6 --gid skiftel --groups pwrp --home-dir /home/skiftel skiftel; then
+    echo "-- User skiftel added..."
   fi
 
-  if [ ! -e /home/skiftel ]; then
-    mkdir /home/skiftel
-    cp /usr/pwrrt/cnf/user/.bashrc /home/skiftel
-    cp /usr/pwrrt/cnf/user/.bash_profile /home/skiftel
-#    cp /usr/pwrrt/cnf/user/.mwmrc /home/skiftel
+  # If all went well we copy proview specific startup scripts to the home folder
+  if [ -e /home/skiftel ]; then
     cp /usr/pwrrt/cnf/user/.rtt_start /home/skiftel
     chmod a+x /home/skiftel/.rtt_start
     cp /usr/pwrrt/cnf/user/.xtt_start /home/skiftel
     chmod a+x /home/skiftel/.xtt_start
-#    cp /usr/pwrrt/cnf/user/.xsession /home/skiftel
 
-    chown -R pwrp /home/skiftel
+    # And change group ownership of skiftel's home folder to pwrp
     chgrp -R pwrp /home/skiftel
   fi
 fi
 
-if getent passwd b55 > /dev/null; then
-  new_user=1
+# Setup the operator group memberships
+groups="pwrp"
+getent group audio >/dev/null && groups+=",audio"
 
-  # Check if group audio exist
-  if getent group audio > /dev/null; then
-    groups="pwrp,audio"
-  else
-    groups="pwrp"
+# Add the user b55
+if getent passwd b55 >/dev/null; then
+   echo "-- User b55 already exist. OK!"
+else
+  if useradd --create-home --shell /bin/bash --password aaQPClsglxJP6 --gid b55 --groups $groups --home-dir /home/b55 b55; then
+    echo "-- User b55 added..."
   fi
 
-  if useradd -s /bin/bash -p aaQPClsglxJP6 -g b55 -G $groups -d /home/b55 b55; then
-    echo "-- user b55 added"
-  fi
-  if [ ! -e /home/b55 ]; then
-    mkdir /home/b55
-    cp /usr/pwrrt/cnf/op/.bashrc /home/b55
-    cp /usr/pwrrt/cnf/op/.bash_profile /home/b55
-#    cp /usr/pwrrt/cnf/op/.mwmrc /home/b55
+  if [ -e /home/b55 ]; then
     cp /usr/pwrrt/cnf/op/.rtt_start /home/b55
     chmod a+x /home/b55/.rtt_start
     cp /usr/pwrrt/cnf/op/.xtt_start /home/b55
     chmod a+x /home/b55/.xtt_start
-#    cp /usr/pwrrt/cnf/op/.xsession /home/b55
 
     chown -R b55 /home/b55
     chgrp -R pwrp /home/b55
-    chmod g+rwx /home/b55
+    chmod g+rws /home/b55
   fi
 fi
 
-if getent passwd b66 > /dev/null; then
-  new_user=1
-
-  # Check if group audio exist
-  if getent group audio > /dev/null; then
-    groups="pwrp,audio"
-  else
-    groups="pwrp"
+if getent passwd b66 >/dev/null; then
+   echo "-- User b66 already exist. OK!"
+else
+  if useradd --create-home --shell /bin/bash --password 1P4JdWA5HqSMQ --gid b66 --groups $groups --home-dir /home/b66 b66; then
+    echo "-- User b66 added..."
   fi
 
-  if useradd -s /bin/bash -p aae.nHgHbfUpw -g b66 -G $groups -d /home/b66 b66; then
-    echo "-- user b66 added"
-  fi
-  if [ ! -e /home/b66 ]; then
-    mkdir /home/b66
-    cp /usr/pwrrt/cnf/op/.bashrc /home/b66
-    cp /usr/pwrrt/cnf/op/.bash_profile /home/b66
-#    cp /usr/pwrrt/cnf/op/.mwmrc /home/b66
+  if [ -e /home/b66 ]; then
     cp /usr/pwrrt/cnf/op/.rtt_start /home/b66
-    chmod a+x /home/b66/.rtt_start
+    chmod a+x /home/b55/.rtt_start
     cp /usr/pwrrt/cnf/op/.xtt_start /home/b66
-    chmod a+x /home/b66/.xtt_start
-#    cp /usr/pwrrt/cnf/op/.xsession /home/b66
+    chmod a+x /home/b55/.xtt_start
 
     chown -R b66 /home/b66
     chgrp -R pwrp /home/b66
-    chmod g+rwx /home/b66
+    chmod g+rws /home/b66
   fi
 fi
 
 chown -R pwrp /usr/pwrrt
 chgrp -R pwrp /usr/pwrrt
 
-chmod u+s /usr/pwrrt/exe/rt_ini
-chmod u+s /usr/pwrrt/exe/rt_rtt
+setcap cap_net_admin,cap_net_raw,cap_net_broadcast+eip /usr/pwrrt/exe/rt_ini
+
+#chmod u+s /usr/pwrrt/exe/rt_ini
+#chmod u+s /usr/pwrrt/exe/rt_rtt
 #chmod u+s /usr/pwrrt/exe/rt_xtt
-chmod u+s /usr/pwrrt/exe/rt_bck
-chmod u+s /usr/pwrrt/exe/rt_gdhget
-chown root /usr/pwrrt/exe/rs_remote_alcm
-chmod u+s /usr/pwrrt/exe/rs_remote_alcm
-if getent group dialout > /dev/null; then
-  chgrp dialout /usr/pwrrt/exe/rs_remote_serial
-  chmod ug+s /usr/pwrrt/exe/rs_remote_serial
-  chgrp dialout /usr/pwrrt/exe/rs_remote_3964r
-  chmod ug+s /usr/pwrrt/exe/rs_remote_3964r
-fi
-if [ -e /usr/pwrrt/exe/rt_powerlink ]; then
-  chown root /usr/pwrrt/exe/rt_powerlink
-  chmod u+s /usr/pwrrt/exe/rt_powerlink
-fi
-chown root /usr/pwrrt/exe/rt_mozilla
-chmod u+s /usr/pwrrt/exe/rt_mozilla
+#chmod u+s /usr/pwrrt/exe/rt_bck
+#chmod u+s /usr/pwrrt/exe/rt_gdhget
+#chown root /usr/pwrrt/exe/rs_remote_alcm
+#chmod u+s /usr/pwrrt/exe/rs_remote_alcm
+#if getent group dialout > /dev/null; then
+#  chgrp dialout /usr/pwrrt/exe/rs_remote_serial
+#  chmod ug+s /usr/pwrrt/exe/rs_remote_serial
+  #chgrp dialout /usr/pwrrt/exe/rs_remote_3964r
+  #chmod ug+s /usr/pwrrt/exe/rs_remote_3964r
+#fi
+#if [ -e /usr/pwrrt/exe/rt_powerlink ]; then
+  #chown root /usr/pwrrt/exe/rt_powerlink
+  #chmod u+s /usr/pwrrt/exe/rt_powerlink
+#fi
+#chown root /usr/pwrrt/exe/rt_mozilla
+#chmod u+s /usr/pwrrt/exe/rt_mozilla
 
 # Copy configuration files
 new_cnf=0
@@ -194,30 +143,30 @@ if [ ! -e /etc/proview.cnf ]; then
   new_cnf=1
 fi
 
-# Add pwrp_profile to profile
-if ! grep -q "/etc/pwrp_profile\b" /etc/profile; then
-  cat >> /etc/profile <<-EOF
-	if [ -e /etc/pwrp_profile ]; then
-	  source /etc/pwrp_profile
-	fi
-EOF
-fi
+# Source pwrp_profile from both profile and bash.bashrc
+for cnf_file in /etc/profile /etc/bash.bashrc; do
+  if ! grep -q "/etc/pwrp_profile\b" ${cnf_file}; then
+  	cat >> ${cnf_file} <<-EOF
+		[[ -e /etc/pwrp_profile ]] && . /etc/pwrp_profile
+		EOF
+  fi
+done
 
 # Create startup link
-set +e
-checklink=`eval ls /etc/rc2.d/S90pwr 2>/dev/null`
-set -e
-if [ "$checklink" != "" ]; then
-  rm /etc/rc2.d/S90pwr
-fi
-ln -s /etc/init.d/pwr /etc/rc2.d/S90pwr
+# set +e
+# checklink=`eval ls /etc/rc2.d/S90pwr 2>/dev/null`
+# set -e
+# if [ "$checklink" != "" ]; then
+#   rm /etc/rc2.d/S90pwr
+# fi
+# ln -s /etc/init.d/pwr /etc/rc2.d/S90pwr
 
-set +e
-checklink=`eval ls /etc/rc2.d/S91gdhserver 2>/dev/null`
-set -e
-if [ "$checklink" != "" ]; then
-  rm /etc/rc2.d/S91gdhserver
-fi
+# set +e
+# checklink=`eval ls /etc/rc2.d/S91gdhserver 2>/dev/null`
+# set -e
+# if [ "$checklink" != "" ]; then
+#   rm /etc/rc2.d/S91gdhserver
+# fi
 # Obsolete
 #ln -s /etc/init.d/gdhserver /etc/rc2.d/S91gdhserver
 
@@ -324,8 +273,8 @@ EOF
 fi
 
 # Add directories to nginx
-if [ -e /etc/nginx/sites-enabled/default ]; then
-  if ! egrep -q "location /pwrp_web/" /etc/nginx/sites-enabled/default; then
+if [ -e /etc/nginx/sites-available/default ]; then
+  if ! egrep -q "location /pwrp_web/" /etc/nginx/sites-available/default; then
     awk '
 BEGIN {
   inserver = 0;
@@ -365,57 +314,36 @@ BEGIN {
   }
   else
     printf( "%s\n", $0);
-}' /etc/nginx/sites-enabled/default > /etc/nginx/sites-enabled/default.new
+}' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default.new
 
-    mv /etc/nginx/sites-enabled/default.new /etc/nginx/sites-enabled/default
+    cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old
+    mv /etc/nginx/sites-available/default.new /etc/nginx/sites-available/default
+    ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
   fi
 fi
 
-#
-# Set owner on preinstalled I/O systems
-#
-if [ -e /lib/udev/devices/qbus ]; then
-  chown pwrp:pwrp /lib/udev/devices/qbus
-fi
-if [ -e /lib/udev/devices/pbus1 ]; then
-  chown pwrp:pwrp /lib/udev/devices/pbus1
-fi
-if [ -e /lib/udev/devices/pbus2 ]; then
-  chown pwrp:pwrp /lib/udev/devices/pbus2
-fi
-
 changes=0
-if [ $new_user -eq 1 ]; then
-  changes=1
-elif [ $new_cnf -eq 1 ]; then
+if [ $new_cnf -eq 1 ]; then
   changes=1
 elif [ $new_project -eq 1 ]; then
   changes=1
 fi
 
-if [ $changes -ne 0 ]; then
-  echo ""
-  echo ""
-  echo "***********************************************************"
-  echo "  Don't forget to do this :"
-  echo ""
-fi
+echo ""
+echo "***********************************************************"
+echo "  Don't forget to do this :"
+echo ""
 
 if [ $new_cnf -eq 1 ]; then
   echo "-- Enter QcomBusId in /etc/proview.cnf"
 fi
-
-#if [ $new_user -eq 1 ]; then
-#  echo "-- Enter OpPlace object as argument to rt_xtt in /home/b55/.xtt_start"
-#fi
 
 if [ $new_project -eq 1 ]; then
   nodename=`eval uname -n`
   echo "-- Distribute project to $nodename"
 fi
 
-if [ $changes -ne 0 ]; then
-  echo ""
-  echo "***********************************************************"
-  echo ""
-fi
+echo "-- Once you have a project setup, enable the pwr service with:"
+echo "   # systemctl enable pwr"
+echo "***********************************************************"
+echo ""
